### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by zhaojc001** [lxc86739795/vehiclereid_baseline#1]
when i finish the training VeRi，i use the backbong that is resnet50，but i use eval.sh testing，it occurs the error，please help me.
the error is the following：
Extracting feature of image 976:
Extracting feature of image 977:
Extracting feature of image 978:
Extracting feature of image 979:
Extracting feature of image 980:
Extracting feature of image 981:
Extracting feature of image 982:
Traceback (most recent call last):
  File "eval.py", line 269, in <module>
    main()
  File "eval.py", line 118, in main
    evaluate(query_loader, gallery_loader, model)
  File "eval.py", line 138, in evaluate
    for i, (image, pid, camid) in enumerate(query_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 610, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 113, in get
    return ForkingPickler.loads(res)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 256, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 181, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 160, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata

**Comment by MathewXiren** [comment]
Set the number of workers to 0
--workers 0 (default is 4)
